### ISSUE TITLE
'default' is not exported by ./src/css/tailwind.config.js

### ISSUE THREAD

**Issue by ghost** [cruip/vuejs-admin-dashboard-template#1]
Hello, npm run build outputs an error, any idea how to solve ? Thanks @pasqualevitiello 
```
  'default' is not exported by ./src/css/tailwind.config.js, imported by src/utils/Utils.js
  file: /Users/zenati/development/vuejs-admin-dashboard-template/src/utils/Utils.js:2:7
  1: import resolveConfig from 'tailwindcss/resolveConfig';
  2: import tailwindConfigFile from '@tailwindConfig';
            ^
  3: 
  4: export const tailwindConfig = () => {
  error during build:
  Error: 'default' is not exported by ./src/css/tailwind.config.js, imported by src/utils/Utils.js
```

**Comment by pasqualevitiello** [comment]
It seems that something breaks with vite 2.6.0 and up.
Here is what you can do, before we figure out what’s wrong with vite, and release a fix:

• Delete the `node_modules` folder, and the `package-lock.json` file
• Open the `package.json` file, and ensure that vite version is 2.5.7: `"vite": "2.5.7"` (ensure to delete the `^` character)
• Install dependencies again with `npm install`

**Comment by yusrenaltair** [comment]
I faced the same problem with vite 3.0.2. to get over it
vite.config.js
```js
 build: {
    commonjsOptions: {
      transformMixedEsModules: true,
      include: [/src/, /node_modules/] //add this line
    }
  },
  ```

**Comment by pasqualevitiello** [comment]
This commit should resolve the issue: https://github.com/cruip/vuejs-admin-dashboard-template/commit/b6503aab2ae0fefee25b96f8711fb036d9770c5d
