### ISSUE TITLE
'TAILWIND_MODE' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by clabnet** [cruip/vuejs-admin-dashboard-template#2]
yarn install
yarn dev 
throw this error.

**Comment by pasqualevitiello** [comment]
As a Windows user you need to install cross-env (`npm install cross-env —save-dev`) and change the `start` script in `package.json` file to `"start": "cross-env TAILWIND_MODE=watch vite"`

Ref: https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

**Comment by clabnet** [comment]
Grazie Pasquale
