### ISSUE TITLE
Cannot read properties of undefined (reading 'labels') in DoughnutChart

### ISSUE THREAD

**Issue by workings21** [cruip/vuejs-admin-dashboard-template#5]
<img width="712" alt="image" src="https://github.com/cruip/vuejs-admin-dashboard-template/assets/106615753/c1f3a985-b334-42cd-b8be-7f61dd2be208">

Hi I have a little problem with my chart js, so I want to implement DoughnutChart

and I have configured it according to digithub, but the labels under the chart do not appear and the label undefined error appears.

I didn't change anything in the component charts and partials, I just copied and pasted the existing code.

### ini adalah file DoughnutChart.vue

<template>
  <div class="grow flex flex-col justify-center">
    <div>
      <canvas ref="canvas" :data="data" :width="width" :height="height"></canvas>
    </div>
    <div class="px-5 pt-2 pb-6">
      <ul ref="legend" class="flex flex-wrap justify-center -m-1"></ul>
    </div>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted } from 'vue'
import {
  Chart, DoughnutController, ArcElement, TimeScale, Tooltip,
} from 'chart.js'
import 'chartjs-adapter-moment'

// Import utilities
import { tailwindConfig } from '@/utils/Utils'
import { data } from 'autoprefixer'

Chart.register(DoughnutController, ArcElement, TimeScale, Tooltip)

export default {
  name: 'DoughnutChart',
  props: ['data', 'width', 'height'],
  setup(props) {

    const canvas = ref(null)
    const legend = ref(null)
    let chart = null

    onMounted(() => {
      const ctx = canvas.value
      chart = new Chart(ctx, {
        type: 'doughnut',
        data: props.data,
        options: {
          cutout: '80%',
          layout: {
            padding: 24,
          },
          plugins: {
            legend: {
              display: false,
            },
          },
          interaction: {
            intersect: false,
            mode: 'nearest',
          },
          animation: {
            duration: 500,
          },
          maintainAspectRatio: false,
          resizeDelay: 200,
        },
        plugins: [{
          id: 'htmlLegend',
          afterUpdate(c, args, options) {
            const ul = legend.value
            if (!ul) return 'ok'
            // Remove old legend items
            while (ul.firstChild) {
              ul.firstChild.remove()
            }
            // Reuse the built-in legendItems generator
            const items = c.options.plugins.legend.labels.generateLabels(c.data)

            console.log(c.data)
            items.forEach((item) => {
              const li = document.createElement('li')
              li.style.margin = tailwindConfig().theme.margin[1]
              // Button element
              const button = document.createElement('button')
              button.classList.add('btn-xs')
              button.style.backgroundColor = tailwindConfig().theme.colors.white
              button.style.borderWidth = tailwindConfig().theme.borderWidth[1]
              button.style.borderColor = tailwindConfig().theme.colors.slate[200]
              button.style.color = tailwindConfig().theme.colors.slate[500]
              button.style.boxShadow = tailwindConfig().theme.boxShadow.md
              button.style.opacity = item.hidden ? '.3' : ''
              button.onclick = () => {
                c.toggleDataVisibility(item.index, !item.index)
                c.update()
              }
              // Color box
              const box = document.createElement('span')
              box.style.display = 'block'
              box.style.width = tailwindConfig().theme.width[2]
              box.style.height = tailwindConfig().theme.height[2]
              box.style.backgroundColor = item.fillStyle
              box.style.borderRadius = tailwindConfig().theme.borderRadius.sm
              box.style.marginRight = tailwindConfig().theme.margin[1]
              box.style.pointerEvents = 'none'
              // Label
              const label = document.createElement('span')
              label.style.display = 'flex'
              label.style.alignItems = 'center'
              const labelText = document.createTextNode(item.text)
              label.appendChild(labelText)
              li.appendChild(button)
              button.appendChild(box)
              button.appendChild(label)
              ul.appendChild(li)
            })
          },
        }],
      })
    })

    onUnmounted(() => chart.destroy())

    return {
      canvas,
      legend,
    }
  }
}
</script>

**Comment by frankmichel** [comment]
@workings21 Probably too late for you, but I just had the same issue and figured out a solution. In the ChartjsConfig.js you need to also import/register the Legend module. Not sure why this is not needed for the Mosaic sample app. But it does help when copy/pasting single charts.

```js
// ChartjsConfig.js

import { Chart, Tooltip, Legend } from 'chart.js'

Chart.register(Tooltip)
Chart.register(Legend)
```
